name: matlab

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup matlab
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest  # or 'R2024b', etc.

      - name: run unit tests
        run: matlab -batch "startup; results = runtests; assertSuccess(results)"