name: MATLAB CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup matlab
        uses: mathworks/setup-matlab@v2

      - name: run unit tests
        run: matlab -batch "startup; results = runtests; assertSuccess(results)"